global:
  scrape_interval: 15s
  evaluation_interval: 30s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]

rule_files:
  - /etc/prometheus/alert.rules.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "node_exporter"
    static_configs:
      - targets:
          # 여기에 모니터링 대상 서버의 IP:9100을 추가하세요
          - "172.31.122.154:9100"

  - job_name: "dcgm_exporter"
    static_configs:
      - targets:
          # 여기에 모니터링 대상 서버의 IP:9400을 추가하세요
          - "172.31.122.154:9400"


